import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { OAuth2Server } from 'oauth2-mock-server';

// Where the issuer's signing key is cached. Gitignored, and regenerated by
// deleting it.
//
// Persisted rather than generated per run because jwks-rsa caches by `kid`: a
// fresh key on every restart invalidates every token minted before it, and the
// symptom is a 401 on a token that looks perfectly valid. Cached, the mock
// issuer can be restarted without reminting.
//
// This is a throwaway development key and nothing else. It signs tokens that
// only an API explicitly pointed at http://localhost is willing to verify, so
// it grants nothing anywhere else — but it is still a private key, which is
// why it is written at runtime into an ignored file rather than committed.
const KEY_PATH = join(__dirname, '..', '..', '.mock-oidc-key.json');

export const ISSUER_PORT = 8080;
export const ISSUER_URL = `http://localhost:${ISSUER_PORT}`;

// Trailing slash to match Auth0, which stamps `iss` as https://<domain>/. The
// strategy compares that string exactly.
export const ISSUER_CLAIM = `${ISSUER_URL}/`;

// Loads the cached key into a server instance, generating and caching one on
// first use. The instance is not started — `buildToken` needs an issuer, not a
// listening socket, which is what lets tokens be minted offline.
export async function loadIssuer(): Promise<OAuth2Server> {
  const server = new OAuth2Server();

  if (existsSync(KEY_PATH)) {
    await server.issuer.keys.add(JSON.parse(readFileSync(KEY_PATH, 'utf8')));
  } else {
    await server.issuer.keys.generate('RS256');
    const [jwk] = server.issuer.keys.toJSON(true);
    writeFileSync(KEY_PATH, JSON.stringify(jwk, null, 2));
    console.log(`mock-oidc: generated a new signing key at ${KEY_PATH}`);
  }

  return server;
}
